[package]
name = "r2rsplugins"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = "0.9.4"

[build-dependencies]
bindgen = "0.61.0"
cc ="1.0.73"